import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

const Map<String, String> sanskritWordMap = const {
  "I": "अहम् (ahám)",
  "you (singular)": "त्वम् (tvám)",
  "he": "स (sá)",
  "we": "वयम् (vayám)",
  "you (plural)": "यूयम् (yūyám)",
  "they": "ते (té)",
  "this": "इदम् (idám)",
  "that": "तत् (tát)",
  "here": "अत्र (átra)",
  "there": "तत्र (tátra)",
  "who": "क (ká)",
  "what": "किम् (kím)",
  "where": "कुत्र (kútra)",
  "when": "कदा (kadā́)",
  "how": "कथम् (kathám)",
  "not": "न (ná)",
  "all": "सर्व (sárva)",
  "many": "बहु (bahú)",
  "some": "किञ्चिद् (kíñcid)",
  "few": "अल्प (álpa)",
  "other": "अन्य (anyá)",
  "one": "एक (éka)",
  "two": "द्वि (dví)",
  "three": "त्रि (trí)",
  "four": "चतुर् (cátur)",
  "five": "पञ्ज (páñcan)",
  "big": "महत् (mahát)",
  "long": "दीर्घ (dīrghá)",
  "wide": "उरु (urú)",
  "thick": "घन (ghaná)",
  "heavy": "गुरु (gurú)",
  "small": "अल्प (álpa)",
  "short": "ह्रस्व (hrasvá)",
  "narrow": "अंहु (aṃhú)",
  "thin": "तनु (tanú)",
  "woman": "स्त्री (strī́)",
  "man (adult male)": "पुरुष (púruṣa), नर (nára)",
  "man (human being)": "मनुष्य (manuṣyá)",
  "child": "बाल (bā́la), शिशु (śíśu)",
  "wife": "भार्या॑ (bhāryā́)",
  "husband": "पति (páti)",
  "mother": "मातृ (mā́tṛ)",
  "father": "पितृ (pitṛ́)",
  "animal": "पशु (páśu)",
  "fish": "मत्स्य (mátsya)",
  "bird": "वि (ví)",
  "dog": "श्वानः (śvánah)",
  "louse": "यूका (yūkā)",
  "snake": "सर्प (sarpá)",
  "worm": "कृमि (kṛmi)",
  "tree": "वृक्ष (vrkṣá)",
  "forest": "वन (vána)",
  "stick": "दण्ड (daṇḍá)",
  "fruit": "फल (phála)",
  "seed": "भीज (bī́ja)",
  "leaf": "पत्त्र (páttra)",
  "root": "मूल (mū́la)",
  "bark (of a tree)": "त्वच् (tvác)",
  "flower": "पुष्प (púṣpa)",
  "grass": "तृण (tṛṇa)",
  "rope": "रज्जु (rájju)",
  "skin": "चर्मन् (cárman)",
  "meat": "मांस (māṃsá)",
  "blood": "असृज् (ásṛj)",
  "bone": "अस्थि (ásthi)",
  "fat (noun)": "पीवस् (pī́vas), मेदस् (médas)",
  "egg": "अण्ड (aṇḍa)",
  "horn": "शृङ्ग (ṡṛṅgá)",
  "tail": "पुच्छ (púccha)",
  "feather": "पर्ण (parṇá)",
  "hair": "केश (kéśa)",
  "head": "शिरस् (śíras)",
  "ear": "कर्ण (kárṇa)",
  "eye": "अक्षि (ákṣi)",
  "nose": "नासिक (nā́sika)",
  "mouth": "मुख (múkha)",
  "tooth": "दत्/दन्त (dát/dánta)",
  "tongue (organ)": "जिह्व/जिह्वा (jihvá/jihvā́)",
  "fingernail": "नख (nakhá)",
  "foot": "पद (padá)",
  "leg": "जङ्घ (jáṅgha)",
  "knee": "जानु (jā́nu)",
  "hand": "हस्त (hásta), पाणि (pāṇí)",
  "wing": "पक्ष (pakṣá)",
  "belly": "उदर (udára)",
  "guts": "गुद (gudá)",
  "neck": "कण्ठ (kaṇṭhá)",
  "back": "पृष्ठ (pṛṣṭhá)",
  "breast": "स्तन (stána)",
  "heart": "हृद् (hṛd), हृदय (hṛdaya)",
  "liver": "यकृत् (yákṛt)",
  "to drink": "पा – पिबति (pā – píbati)",
  "to eat": "अद् – अत्ति (ad – átti)",
  "to bite": "दंश् – दंशति (daṃś – dáṃśati)",
  "to suck": "धे – धयति (dhe – dháyati)",
  "to spit": "ष्ठिव् – ष्ठिवति/ष्ठीव्यति (ṣṭiv – ṣṭívati/ṣṭhī́vyati)",
  "to vomit": "वम् – वमति (vam – vámati)",
  "to blow": "वा – वाति (vā – vā́ti)",
  "to breathe": "अन् – अनिति (an- ániti)",
  "to laugh": "स्मि – स्मयते (smi – smáyate), हस्- हसति (has – hásati)",
  "to see":
      "पश्- पश्यति (paś – páśyati; only in the present system), दृश् (dṛś;",
  "": "everywhere else)",
  "to hear": "श्रु- शृणोति (śru – śṛṇóti)",
  "to know": "ज्ञा- जानाति (jñā – jānā́ti)",
  "to think": "मन्- मनुते (man – manuté), चिन्त् – चिन्तयति (cint – cintayati)",
  "to smell": "घ्रा- जिघ्रति (ghrā – jíghrati)",
  "to fear": "भी – बिभेति (bhī – bibhéti)",
  "to sleep": "स्वप्- स्वपिति (svap – svápiti)",
  "to live": "जीव्- जीवति (jīv – jī́vati)",
  "to die": "मृ – म्रियते (mṛ – mriyáte)",
  "to kill": "हन् – हन्ति (han – hánti)",
  "to fight": "युध् – युध्यते (yudh – yúdhyate)",
  "to hunt": "मृग् – मृगयते (mṛga – mṛgáyate)",
  "to hit": "हन् – हन्ति (han – hánti), तड् – ताडयति (taḍ – tāḍáyati)",
  "to cut": "कृत् – कृन्तति (kṛt – kṛntáti)",
  "to split": "भिद्- भिनत्ति (bhid – bhinátti)",
  "to stab": "व्यध्- विधति (vyadh – vídhyati)",
  "to scratch": "लिख् – – लिखति (likh – likháti)",
  "to dig": "खन् – खनति (khan – khánati)",
  "to swim": "प्लु- प्लवते (plu – plávate)",
  "to fly": "पत् – पतति (pat – pátati)",
  "to walk": "इ – एति (i – éti), गम् – गच्छति (gam – gácchati)",
  "to come": "आगम् – आगच्छति (āgam – ā́gacchati)",
  "to lie (as in a bed)": "शी- शेते (śī – śéte)",
  "to sit": "सद् – सीदति (sad – sī́dati)",
  "to stand": "स्था – तिष्ठति (sthā – tíṣṭhati)",
  "to turn (intransitive)": "वृत् – वर्तते (vṛt – vártate)",
  "to fall": "पद् – पद्यते (pad – pádyate)",
  "to give": "दा – ददाति (dā – dádāti)",
  "to hold": "धृ – धरति (dhṛ – dhárati)",
  "to squeeze": "मृद् – मृद्नाति (mṛd – mṛdnā́ti)",
  "to rub": "घृष् – घर्षति (ghṛṣ – ghárṣati)",
  "to wash": "क्षल् – क्षालयति (kṣal – kṣā́layati)",
  "to wipe": "मृज् – मार्ष्टि (mṛj – mā́rṣṭi)",
  "to pull": "कृष् – कर्षति (kṛṣ – kárṣati)",
  "to push": "नुद् – नुदति (nud – nudáti)",
  "to throw": "क्षिप् – क्षिपति (kṣip – kṣipáti)",
  "to tie": "बन्ध् – बध्नाति (bandh – badhnā́ti)",
  "to sew": "सिव् – सीव्यति (siv – sī́vyati)",
  "to count": "गण् – गणयति (gaṇ – gáṇayati), कल् – कलते (kal – kálate)",
  "to say": "वच् – वक्ति (vac – vákti)",
  "to sing": "गै- गायति (gāi – gā́yati )",
  "to play": "दिव् – दीव्यति (div – dī́vyati)",
  "to float": "प्लु – प्लवते (plu – plávate)",
  "to flow": "सृ – सरति (sṛ – sárati), क्षर् – क्षरति (kṣar -kṣárati)",
  "to freeze": "श्यै – शीयते (śyāi – śī́yate)",
  "to swell": "श्वि – श्वयति (śvi – śváyati)",
  "sun": "सूर्य (sū́rya)",
  "moon": "मास (mā́sa), चन्द्रमस् (candramas), चन्द्र (candra)",
  "star": "नक्षत्र (nákshatra), स्तृ (stṛ)",
  "water": "जल (jalá), वारि (vā́ri)",
  "rain": "वर्ष (varṣá)",
  "river": "नदी (nadī́)",
  "lake": "सरस् (sáras)",
  "sea": "उदधि (udadhí)",
  "salt": "लवण (lavaṇá)",
  "stone": "अश्मन् (aśman)",
  "sand": "पांसु (pāṃsú), शिकता (síkatā)",
  "dust": "रेणु (reṇú)",
  "earth": "क्षम् (kṣám), पृथिवी (pṛithivī́)",
  "cloud": "नभस् (nábhas), मेघ (meghá)",
  "fog": "मिह् (míh)",
  "sky": "आकाश (ā́kā́śa)",
  "wind": "वायु (vāyú), वात (vā́ta)",
  "snow": "हिम (himá), तुषार (tuṣāra), तुहिन (tuhina)",
  "ice": "हिम (himá)",
  "smoke": "धूम (dhūmá)",
  "fire": "अग्नि (agní)",
  "ash": "आस (ā́sa)",
  "to burn": "दहति (dahati)",
  "road": "अध्वन् (ádhvan), मार्ग (mārga), रथ्या (rathyā)",
  "mountain": "गिरि (girí), पर्वत (párvata)",
  "red": "रक्त (rakta), रोहित (róhita)",
  "green": "हरित् (harít)/हरित (harita), पालााश (pā́lāśa)/पलााश (palāśa)",
  "yellow": "पीत (pīta)/पीतल (pītala)",
  "white": "श्वेत (śvetá)",
  "black": "कृष्ण (kṛṣṇá)",
  "night": "रात्र (rātrá)",
  "day": "द्यु (dyú), अहर् (áhar)",
  "year": "वर्ष (varṣá), संवत्सर (saṃvatsara)/संवत् (saṃvat)",
  "warm": "तप्त (taptá), घर्म (gharmá)",
  "cold": "शीत (śītá)",
  "full": "पूर्ण (pūrṇá)",
  "new": "नव (náva), नूतन (nū́tana)",
  "old": "जीर्ण (jīrṇá), वृद्ध (vr̥ddhá)",
  "good": "वसु (vásu), भद्र (bhadrá)",
  "bad": "पाप (pāpá)",
  "rotten": "पूति (pū́ti)",
  "dirty": "मलिन (malina), समल (samala)",
  "straight": "ऋजु (r̥jú)",
  "round": "वृत्त (vr̥ttá), वर्तुल (vartula)",
  "sharp (as a knife)": "तीक्ष्ण (tīkṣṇá)",
  "dull (as a knife)": "कुण्ठ (kuṇṭha)",
  "smooth": "श्लक्ष्ण (ślakṣṇá), स्निग्ध (snigdhá)",
  "wet": "आर्द्र (ārdrá), क्लिन्न (klinná)",
  "dry": "शुष्क (śúṣka)",
  "correct": "शुद्ध (śuddhá), सत्य (satyá)",
  "near": "नेद (neda, adj.), प्रति (prati, prep.)",
  "far": "दूर (dūrá)",
  "right": "दक्षिण (dákṣiṇa)"
};
List sanskritWords = [];
List englishWords = [];

class LearnPage extends StatefulWidget {
  @override
  _LearnPageState createState() => _LearnPageState();
}

class _LearnPageState extends State<LearnPage> {
  ScrollController controller = ScrollController();

  @override
  Widget build(BuildContext context) {
    sanskritWordMap.forEach((key, value) {
      sanskritWords.add(value);
      englishWords.add(key);
    });
    return Scrollbar(
      controller: controller,
      isAlwaysShown: true,
      child: Container(
        padding: const EdgeInsets.all(15),
        child: GridView.builder(
          controller: controller,
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 3,
              mainAxisSpacing: 5,
              crossAxisSpacing: 5,
              childAspectRatio: 1),
          itemCount: sanskritWordMap.length,
          itemBuilder: (context, index) => GestureDetector(
            onTap: () {
              showDialog(
                barrierDismissible: true,
                context: context,
                builder: (context) => AlertDialog(
                  title: Text(sanskritWords[index]),
                  content: Text('MEANING : ${englishWords[index]}'),
                ),
              );
            },
            child: Container(
              decoration: BoxDecoration(
                  color: Colors.grey, borderRadius: BorderRadius.circular(15)),
              child: Center(
                child: Text(
                  sanskritWords[index],
                  style: const TextStyle(fontSize: 15, color: Colors.white),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
