// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK4O6qMhq4Py92kI1Jtm_9rvoP1yQvtok',
    appId: '1:845002351889:android:d901ab0ca2fa8da92ed8b0',
    messagingSenderId: '845002351889',
    projectId: 'sanskritive',
    storageBucket: 'sanskritive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMBkRgOP32wHZMCCGCciSgwkWo3aoNPg0',
    appId: '1:845002351889:ios:2c1286f3f63e96d92ed8b0',
    messagingSenderId: '845002351889',
    projectId: 'sanskritive',
    storageBucket: 'sanskritive.appspot.com',
    androidClientId: '845002351889-quhvi2nsek79j0khtgukfrn2nf270b05.apps.googleusercontent.com',
    iosClientId: '845002351889-9lurhp6sbittsq8n8im19l0kv5dutvf7.apps.googleusercontent.com',
    iosBundleId: 'com.sanskrit.sanskritProject',
  );
}
